require('lazy').setup {
  spec = {
    { import = 'plugins.attempt' },
    { import = 'plugins.blink' },
    { import = 'plugins.bufdelete' },
    { import = 'plugins.conform' },
    { import = 'plugins.floaterm' },
    { import = 'plugins.floating-help' },
    { import = 'plugins.gitsigns' },
    { import = 'plugins.harpoon' },
    { import = 'plugins.inc-rename' },
    { import = 'plugins.indent-blankline' },
    { import = 'plugins.lazydev' },
    { import = 'plugins.mini' },
    { import = 'plugins.neovim-tips' },
    { import = 'plugins.noice' },
    -- { import = 'plugins.no-neck-pain' },
    { import = 'plugins.nvim-autopairs' },
    { import = 'plugins.nvim-dap' },
    { import = 'plugins.nvim-lspconfig' },
    { import = 'plugins.nvim-treesitter' },
    { import = 'plugins.nvim-ufo' },
    { import = 'plugins.smart-backspace' },
    { import = 'plugins.snacks' },
    { import = 'plugins.statuscol' },
    { import = 'plugins.telescope' },
    { import = 'plugins.todo-comments' },
    { import = 'plugins.tokyonight' },
    { import = 'plugins.trouble' },
    { import = 'plugins.which-key' },
  },
  ui = {
    border = 'rounded',
    -- If you are using a Nerd Font: set icons to an empty table which will use the
    -- default lazy.nvim defined Nerd Font icons, otherwise define a unicode icons table
    icons = vim.g.have_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
}
